seed: 2333

dataset:
  val_ratio: 0.2

model:
  in_channels: 1
  num_classes: 10

optim:
  max_epochs: 500
  batch_size: 128
  lr: 0.01
  # betas: [0.9, 0.99]
  warmup_steps: 100
  min_lr_ratio: 0.00001
  momentum: 0.9
  